name: Deploy

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  dockerhub:
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'smarkets/marge-bot' }}  # Only run from main repo
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Dockerize
      run: make dockerize
    - name: Deploy to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # GitHub Actions have GITHUB_REF as `refs/heads/<branch>` or `refs/tags/<tag>`, clean it up
      run: make docker-push VERSION="$(echo $GITHUB_REF | sed 's!^refs/\(heads\|tags\)/!!')"
