name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PY_COLORS: 1

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        poetry-version:
          - '2.0.1'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry==${{ matrix.poetry-version }}
      - name: Install requirements
        run: poetry install
      - name: Run flake8
        run: poetry run flake8 marge tests
      - name: Run pylint
        run: poetry run pylint marge tests
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        poetry-version:
          - '2.0.1'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry==${{ matrix.poetry-version }}
      - name: Install requirements
        run: poetry install
      - name: Run tests
        run: poetry run pytest
  dockerize:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Dockerize
        run: make dockerize
